// Generated by gen_codec_vectors.py (this directory) from c2@408d6f2's decode_data:
// `cd ../c2 && uv run python ../r2/crates/r2-core/tests/support/gen_codec_vectors.py`.
// Do not edit by hand.
// (Regenerate, then `cargo fmt`.)
/// (input, Ok((data hex, format)) | Err((message, hint)))
pub type Outcome = Result<(&'static str, &'static str), (&'static str, Option<&'static str>)>;
pub const DECODE: &[(&str, Outcome)] = &[
    (
        "-----BEGIN X----------END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----AAAA=-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141413d0a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----AAAA====-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141413d3d3d3d0a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----AA=-----END X-----",
        Err((
            "malformed PEM: body of the X block is not valid base64",
            None,
        )),
    ),
    (
        "-----BEGIN X -----AAAA-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----AAAA-----END X -----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X  Y-----AAAA-----END X  Y-----",
        Ok((
            "2d2d2d2d2d424547494e20582020592d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582020592d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN x-----AAAA-----END x-----",
        Ok((
            "2d2d2d2d2d424547494e20782d2d2d2d2d0a414141410a2d2d2d2d2d454e4420782d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN 1-----AAAA-----END 1-----",
        Ok((
            "2d2d2d2d2d424547494e20312d2d2d2d2d0a414141410a2d2d2d2d2d454e4420312d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN -----AAAA-----END -----",
        Err((
            "malformed PEM: no complete BEGIN/END block found",
            Some("a PEM block is '-----BEGIN <LABEL>----- … -----END <LABEL>-----'"),
        )),
    ),
    (
        "-----BEGIN X-----AAAA-----END !----- -----END X-----",
        Err((
            "malformed PEM: body of the X block is not valid base64",
            None,
        )),
    ),
    (
        "-----BEGIN A-----AAAA-----BEGIN B-----BBBB-----END B-----",
        Err(("malformed PEM: 'BEGIN A' closed by 'END B'", None)),
    ),
    (
        "-----BEGIN X-----\r\nAAAA\r\nAAAA\r\n-----END X-----\r\n",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a41414141414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,00\n\nAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c30300a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,00\nAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c30300a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\n\n\nProc-Type: 4,ENCRYPTED\n\nAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\n  Proc-Type:   4,ENCRYPTED  \n\n  AA AA  \n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a50726f632d547970653a202020342c454e435259505445440a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nProc-Type: 4\nnot-a-header line\nAAAA\n-----END X-----",
        Err((
            "malformed PEM: body of the X block is not valid base64",
            None,
        )),
    ),
    (
        "-----BEGIN X-----\nA1: x\nB-2: y\n\nAAAA\nBBBB\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a41313a20780a422d323a20790a0a41414141424242420a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----Proc-Type: inline AAAA-----END X-----",
        Err((
            "malformed PEM: the X block has encapsulated headers but no base64 body",
            Some("paste the block with its line breaks intact"),
        )),
    ),
    (
        "-----BEGIN X-----\nProc-Type: 4\n\n\n\nAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a50726f632d547970653a20340a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nProc-Type: 4\n-----END X-----",
        Err((
            "malformed PEM: the X block has encapsulated headers but no base64 body",
            Some("paste the block with its line breaks intact"),
        )),
    ),
    (
        "-----BEGIN X-----\nAAAA\u{a0}BBBB\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a41414141424242420a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nAAAA\u{1c}BBBB\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a41414141424242420a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nAAAA\u{2028}BBBB\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a41414141424242420a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    // c2 CRASH: ValueError: string argument should contain only ASCII characters
    (
        "-----BEGIN X-----\nAAAAé\n-----END X-----",
        Err(("<c2 crash: ValueError>", None)),
    ),
    (
        "-----BEGIN X-----\nAAAA\n-----END X----- trailing -----BEGIN Y-----BBBB-----END Y-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a2d2d2d2d2d424547494e20592d2d2d2d2d0a424242420a2d2d2d2d2d454e4420592d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nAAAA\n-----END X----------BEGIN Y-----\nBBBB\n-----END Y-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a2d2d2d2d2d424547494e20592d2d2d2d2d0a424242420a2d2d2d2d2d454e4420592d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "  pem:-----BEGIN X-----AAAA-----END X-----  ",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "pem: -----BEGIN X-----\nDEK-Info: a b c\n\nAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a44454b2d496e666f3a2061206220630a0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "PEM:-----BEGIN X-----AAAA-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "HEX:dead",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "0Xdead",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "0x0xdead",
        Err((
            "forced hex decode failed",
            Some("hex is an even number of [0-9a-fA-F] digits (whitespace ignored)"),
        )),
    ),
    (
        "hex:0xdead",
        Err((
            "forced hex decode failed",
            Some("hex is an even number of [0-9a-fA-F] digits (whitespace ignored)"),
        )),
    ),
    (
        "b64:SGVsbG8",
        Err((
            "forced base64 decode failed",
            Some("base64 uses [A-Za-z0-9+/] with '=' padding to a multiple of 4"),
        )),
    ),
    (
        "b64:SGVsbG8==",
        Err((
            "forced base64 decode failed",
            Some("base64 uses [A-Za-z0-9+/] with '=' padding to a multiple of 4"),
        )),
    ),
    ("b64:SGVs\u{a0}bG8=", Ok(("48656c6c6f", "base64"))),
    ("\u{a0}de ad\u{3000}", Ok(("dead", "hex"))),
    ("de\u{1c}ad", Ok(("dead", "hex"))),
    (
        "dé",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    ("AB==", Ok(("00", "base64"))),
    ("AR==", Ok(("01", "base64"))),
    (
        "AAAA====",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "A===",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "SGVsbG8=SGVsbG8=",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    ("+/+/", Ok(("fbffbf", "base64"))),
    (
        "-_-_",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "0",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    ("00", Ok(("00", "hex"))),
    (
        "",
        Err(("empty input", Some("paste hex, base64 or PEM data"))),
    ),
    (
        "\u{3000}",
        Err(("empty input", Some("paste hex, base64 or PEM data"))),
    ),
    (
        "-----BEGIN-----",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "-----BEGIN X-----",
        Err((
            "malformed PEM: no complete BEGIN/END block found",
            Some("a PEM block is '-----BEGIN <LABEL>----- … -----END <LABEL>-----'"),
        )),
    ),
    (
        "----BEGIN X-----AAAA-----END X-----",
        Err((
            "not hex, base64 or PEM",
            Some("force with hex:/b64:/pem: prefix"),
        )),
    ),
    (
        "x -----BEGIN X-----AAAA-----END X----- y",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "LS0tLS1CRUdJTiBYLS0tLS1BQUFBLS0tLS1FTkQgWC0tLS0t",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "2d2d2d2d2d424547494e20582d2d2d2d2d41414141 2d2d2d2d2d454e4420582d2d2d2d2d",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "2d2d2d2d2d424547494e",
        Err((
            "malformed PEM: no complete BEGIN/END block found",
            Some("a PEM block is '-----BEGIN <LABEL>----- … -----END <LABEL>-----'"),
        )),
    ),
    (
        "LS0tLS1CRUdJTg==",
        Err((
            "malformed PEM: no complete BEGIN/END block found",
            Some("a PEM block is '-----BEGIN <LABEL>----- … -----END <LABEL>-----'"),
        )),
    ),
    (
        "-----BEGIN X-----\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141410a414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141410a414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141410a41414141414141410a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
    (
        "-----BEGIN X-----\nQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB\nQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB\n-----END X-----",
        Ok((
            "2d2d2d2d2d424547494e20582d2d2d2d2d0a515546425155464251554642515546425155464251554642515546425155464251554642515546425155464251554642515546425155464251554642515546420a515546425155464251554642515546425155464251554642515546425155464251554642515546425155464251554642515546425155464251554642515546420a2d2d2d2d2d454e4420582d2d2d2d2d0a",
            "pem",
        )),
    ),
];
