"""Generate rich-15 panel vectors for r2 R1 renderer tests (error_panel, hex_panel)."""
import io, sys
from rich.console import Console
from c2.console import render
from c2.core.errors import ConsoleError

def rendered(renderable, width):
    buf = io.StringIO()
    Console(file=buf, force_terminal=False, width=width).print(renderable)
    out = buf.getvalue()
    assert out.endswith("\n")
    return out[:-1]

def rs(s):
    # Rust string literal (escape \ " and control chars)
    out = []
    for ch in s:
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7f: out.append("\\u{%x}" % ord(ch))
        else: out.append(ch)
    return '"' + "".join(out) + '"'

long_msg = ("cannot load PKCS#11 library /usr/lib/softhsm/libsofthsm2.so: "
            "/usr/lib/softhsm/libsofthsm2.so: cannot open shared object file: No such file or directory")
errors = [
    ("boom happened", "try again"),
    ("just broken", None),
    ("x", None),
    ("", None),
    ("e", "h"),
    ("unknown command 'helpp'", "did you mean: help"),
    (long_msg, "check providers.pkcs11[].library in the configuration"),
    ("a" * 100, None),
    ("word " * 30, "hint " * 25),
    ("first line\nsecond line", "multi\nline hint"),
    ("ключ не найден: 'метка'", "проверьте метку"),
    ("日本語のエラーメッセージです。とても長いメッセージがここに来ます。" * 2, None),
    ("tab\there", None),
    ("trailing spaces   ", None),
    ("  leading spaces", "  hint with leading"),
    ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbb ccc", None),
    ("short then " + "x" * 90 + " tail", "z"),
    ("no login: run `login softhsm`", "markup [bold]not[/bold] interpreted"),
    ("x" * 76, None),
    ("x" * 77, None),
    ("x" * 75, "y" * 76),
    ("a b", "c" * 200),
    ("", "only hint"),
]
widths = [80, 200, 40, 20, 12, 9]

print('// Generated by gen_rich_panels.py (this directory) with rich 15.0.0 in the c2@408d6f2 venv:')
print('// `cd ../c2 && uv run python ../r2/crates/r2-core/tests/support/gen_rich_panels.py`.')
print('// Expected = `Console(file=StringIO(), force_terminal=False, width=W).print(panel)` minus the')
print('// final newline. Do not edit by hand.')
print('// (Regenerate, then `cargo fmt`.)')
print("pub const ERROR_PANELS: &[(&str, Option<&str>, usize, &str)] = &[")
for msg, hint in errors:
    for w in widths:
        out = rendered(render.error_panel(ConsoleError(msg, hint=hint)), w)
        print(f"    ({rs(msg)}, {('Some(' + rs(hint) + ')') if hint is not None else 'None'}, {w}, {rs(out)}),")
print("];")

hexes = [
    (bytes(range(8)), 2, 4, None),
    (b"", 2, 32, None),
    (b"", 2, 32, "ciphertext"),
    (bytes(range(32)), 2, 32, None),
    (bytes(range(32)), 2, 32, "ciphertext"),
    (bytes(range(40)), 2, 32, "ciphertext"),
    (bytes(range(64)), 2, 32, "signature"),
    (bytes(range(256)), 2, 32, "data"),
    (bytes(range(1)), 2, 32, None),
    (bytes(range(1)), 2, 32, "a much longer title than content"),
    (bytes(range(3)), 2, 32, "t"),
    (bytes(range(40)), 0, 0, "continuous"),
    (bytes(range(40)), 1, 16, "group1"),
    (bytes(range(40)), 4, 8, "group4"),
    (bytes(range(40)), 0, 16, None),
    (bytes(range(100)), 2, 32, "x" * 120),
    (b"\x01\x02", 2, 32, "ciphertext — [#custom]"),
    (b"\x01\x02", 2, 32, "line\nbreak"),
    (bytes(range(17)), 2, 32, "ключ"),
    (bytes(range(5)), 3, 2, None),
]
hwidths = [80, 200, 40, 20, 10]
print("/// (data, hex_group, hex_width, title, console width, rich output)")
print("pub type HexCase = (&'static [u8], usize, usize, Option<&'static str>, usize, &'static str);")
print("pub const HEX_PANELS: &[HexCase] = &[")
for data, g, hw, title in hexes:
    for w in hwidths:
        out = rendered(render.hex_panel(data, group=g, width=hw, title=title), w)
        dat = "&[" + ", ".join(str(b) for b in data) + "]"
        print(f"    ({dat}, {g}, {hw}, {('Some(' + rs(title) + ')') if title is not None else 'None'}, {w}, {rs(out)}),")
print("];")
