"""Generate rich-15 vectors for r2 R1 renderer tests: error_panel, hex_panel, generic panels,
plain text (`console.print(str, markup=False)`), caret rows, and `cell_len` widths."""
import io, sys, unicodedata
from rich.cells import cell_len
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich._unicode_data import load as load_cell_table
from c2.console import render
from c2.core.errors import ConsoleError

def rendered(renderable, width):
    buf = io.StringIO()
    Console(file=buf, force_terminal=False, width=width).print(renderable)
    out = buf.getvalue()
    assert out.endswith("\n")
    return out[:-1]

def rendered_str(text, width, emoji=True, highlight=True):
    buf = io.StringIO()
    Console(file=buf, force_terminal=False, width=width).print(
        text, markup=False, emoji=emoji, highlight=highlight
    )
    out = buf.getvalue()
    assert out.endswith("\n")
    return out[:-1]

def rs(s):
    # Rust string literal (escape \ " and control chars)
    out = []
    for ch in s:
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7f: out.append("\\u{%x}" % ord(ch))
        # invisible / combining / format / separator code points as escapes (bidi controls
        # would trip rustc's text_direction_codepoint_in_literal lint)
        elif ord(ch) > 0x7f and unicodedata.category(ch)[0] in "MCZ": out.append("\\u{%x}" % ord(ch))
        else: out.append(ch)
    return '"' + "".join(out) + '"'

long_msg = ("cannot load PKCS#11 library /usr/lib/softhsm/libsofthsm2.so: "
            "/usr/lib/softhsm/libsofthsm2.so: cannot open shared object file: No such file or directory")
errors = [
    ("boom happened", "try again"),
    ("just broken", None),
    ("x", None),
    ("", None),
    ("e", "h"),
    ("unknown command 'helpp'", "did you mean: help"),
    (long_msg, "check providers.pkcs11[].library in the configuration"),
    ("a" * 100, None),
    ("word " * 30, "hint " * 25),
    ("first line\nsecond line", "multi\nline hint"),
    ("ключ не найден: 'метка'", "проверьте метку"),
    ("日本語のエラーメッセージです。とても長いメッセージがここに来ます。" * 2, None),
    ("tab\there", None),
    ("trailing spaces   ", None),
    ("  leading spaces", "  hint with leading"),
    ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbb ccc", None),
    ("short then " + "x" * 90 + " tail", "z"),
    ("no login: run `login softhsm`", "markup [bold]not[/bold] interpreted"),
    ("x" * 76, None),
    ("x" * 77, None),
    ("x" * 75, "y" * 76),
    ("a b", "c" * 200),
    ("", "only hint"),
    # rich strips BEL/BS/VT/FF/CR from every Text (R1 fix round 1)
    ("cannot read a\rb: denied", None),
    ("line one\x0bline two", "x"),
    ("\rabababab", "ab\rab\r\r\r\r\rab\rab\r"),
    ("boom", "h\rint"),
    ("cannot read in\x08put.bin: No such file or directory", None),
    ("bell\x07 and form\x0cfeed", "\r"),
    ("\r\x07\x08\x0b\x0c", None),
    # rich cell widths: ZWJ/VS16 graphemes, flags, skin tones, Indic, soft hyphen, combining
    ("label '\u2764\ufe0f' not found", None),
    ("label '\U0001f469\u200d\U0001f4bb' not found", "keys '\U0001f468\u200d\U0001f469\u200d\U0001f467'"),
    ("flags \U0001f1eb\U0001f1f7\U0001f1e9\U0001f1ea and \U0001f44d\U0001f3fd", None),
    ("\u0915\u0941\u0902\u091c\u0940 '\u0928\u092e\u0938\u094d\u0924\u0947' \u0928\u0939\u0940\u0902 \u092e\u093f\u0932\u0940", "\u09a8\u09be\u09ae \u0995\u09bf"),
    ("co\xadoperate e\u0301x \u200b zero", "x\u200d"),
    ("\ufe0f\u200dleading joiners", "#\ufe0f\u20e3 \u263a\ufe0f \u00a9\ufe0f"),
    ("\u17a4\u17d8 \u0605\u070f \uff9e\uff9f", None),
    ("a\tb\tc", "\t\tx"),
    ("a\u2028b c\x85d", "e\u2029f"),
    ("\U0001f469\u200d\U0001f4bb" * 30, None),
]
widths = [80, 200, 40, 20, 12, 9]

print('// Generated by gen_rich_panels.py (this directory) with rich 15.0.0 in the c2@408d6f2 venv:')
print('// `cd ../c2 && uv run python ../r2/crates/r2-core/tests/support/gen_rich_panels.py`')
print('// `  > ../r2/crates/r2-core/tests/support/rich_panels.rs`.')
print('// Expected = `Console(file=StringIO(), force_terminal=False, width=W).print(x)` minus the')
print('// final newline (x = panel, Text, or str with markup=False). Do not edit by hand.')
print('// (Regenerate, then `cargo fmt`.)')
print("pub const ERROR_PANELS: &[(&str, Option<&str>, usize, &str)] = &[")
for msg, hint in errors:
    for w in widths:
        out = rendered(render.error_panel(ConsoleError(msg, hint=hint)), w)
        print(f"    ({rs(msg)}, {('Some(' + rs(hint) + ')') if hint is not None else 'None'}, {w}, {rs(out)}),")
print("];")

hexes = [
    (bytes(range(8)), 2, 4, None),
    (b"", 2, 32, None),
    (b"", 2, 32, "ciphertext"),
    (bytes(range(32)), 2, 32, None),
    (bytes(range(32)), 2, 32, "ciphertext"),
    (bytes(range(40)), 2, 32, "ciphertext"),
    (bytes(range(64)), 2, 32, "signature"),
    (bytes(range(256)), 2, 32, "data"),
    (bytes(range(1)), 2, 32, None),
    (bytes(range(1)), 2, 32, "a much longer title than content"),
    (bytes(range(3)), 2, 32, "t"),
    (bytes(range(40)), 0, 0, "continuous"),
    (bytes(range(40)), 1, 16, "group1"),
    (bytes(range(40)), 4, 8, "group4"),
    (bytes(range(40)), 0, 16, None),
    (bytes(range(100)), 2, 32, "x" * 120),
    (b"\x01\x02", 2, 32, "ciphertext — [#custom]"),
    (b"\x01\x02", 2, 32, "line\nbreak"),
    (bytes(range(17)), 2, 32, "ключ"),
    (bytes(range(5)), 3, 2, None),
    # rich `if self.title:` — an empty title (also after control-code stripping) is none
    (bytes(range(3)), 2, 32, ""),
    (bytes(range(3)), 2, 32, "\r"),
    (b"", 2, 32, ""),
    (bytes(range(2)), 2, 32, "cipher\rtext"),
    (bytes(range(2)), 2, 32, "\U0001f469\u200d\U0001f4bb key"),
    (bytes(range(2)), 2, 32, "a\tb"),
]
hwidths = [80, 200, 40, 20, 10]
print("/// (data, hex_group, hex_width, title, console width, rich output)")
print("pub type HexCase = (&'static [u8], usize, usize, Option<&'static str>, usize, &'static str);")
print("pub const HEX_PANELS: &[HexCase] = &[")
for data, g, hw, title in hexes:
    for w in hwidths:
        out = rendered(render.hex_panel(data, group=g, width=hw, title=title), w)
        dat = "&[" + ", ".join(str(b) for b in data) + "]"
        print(f"    ({dat}, {g}, {hw}, {('Some(' + rs(title) + ')') if title is not None else 'None'}, {w}, {rs(out)}),")
print("];")

# Generic panels: rich `Panel(Text(body), title=Text(t), subtitle=Text(s), expand=False,
# title_align="left", subtitle_align="right")` — r2 `Renderable::Panel` with one span per
# "\n"-separated body line (an empty body list = rich's empty Text).
generics = [
    (None, None, None),
    (None, None, "\t"),
    ("t", None, "\t"),
    ("t", None, None),
    ("", "", "x"),
    ("\r", "\x07", "x"),
    (None, None, "abc"),
    ("t", "sub", "abc"),
    ("title\twith tab", "s\nl", "first line\nsecond line"),
    ("long title " * 5, "subtitle " * 6, "short"),
    (None, None, "x\x0by\x0cz\rw"),
]
gwidths = [80, 40, 12, 7, 6, 5, 4, 3, 2]
print("/// (title, subtitle, body or None for no body line, console width, rich output)")
print("pub type GenericCase = (Option<&'static str>, Option<&'static str>, Option<&'static str>, usize, &'static str);")
print("pub const GENERIC_PANELS: &[GenericCase] = &[")
for title, subtitle, body in generics:
    for w in gwidths:
        panel = Panel(
            Text(body if body is not None else ""),
            title=Text(title) if title is not None else None,
            subtitle=Text(subtitle) if subtitle is not None else None,
            title_align="left",
            subtitle_align="right",
            expand=False,
        )
        out = rendered(panel, w)
        opt = lambda v: ("Some(" + rs(v) + ")") if v is not None else "None"
        print(f"    ({opt(title)}, {opt(subtitle)}, {opt(body)}, {w}, {rs(out)}),")
print("];")

# Plain text exactly as c2 prints a str: `console.print(s, markup=False)` (emoji/highlight
# on). Asserted below: no input contains an emoji shortcode and none depends on highlight
# segment boundaries (§11 D1/D23), so the layout is rich Text's.
texts = [
    "x" * 300,
    "a\tb",
    "\tlead\ttabs\t",
    "",
    "a\n",
    "a\n\nb",
    "usage: load <provider> <aes|rsa|ec|cert|generic|data|auto> [<data>] [--label <l>] [--id <hex>] [--template <file>] [--kek <ref>]",
    "wrote 1234 bytes to /a/very/long/path/that/keeps/going/and/going/" + "segment/" * 12 + "out.bin",
    "word " * 50,
    "trailing spaces" + " " * 100,
    " " * 100 + "leading",
    "carriage\rreturn bell\x07 back\x08space vt\x0b ff\x0c",
    "0001 0203 0405 0607 0809 0a0b 0c0d 0e0f 1011 1213 1415 1617 1819 1a1b 1c1d 1e1f 2021 2223",
    "\u65e5\u672c\u8a9e\u306e\u30c6\u30ad\u30b9\u30c8" * 12,
    "\U0001f469\u200d\U0001f4bb " * 40,
    "a [b] c\n  d",
]
twidths = [80, 200, 40, 10, 3]
print("/// (text, console width, rich output)")
print("pub const TEXTS: &[(&str, usize, &str)] = &[")
for t in texts:
    for w in twidths:
        out = rendered_str(t, w)
        assert out == rendered_str(t, w, emoji=False, highlight=False), t
        print(f"    ({rs(t)}, {w}, {rs(out)}),")
print("];")

# Caret rows laid out by rich (`caret_text`'s Text: row + "\n" + spaces + "^") with r2's
# column (§11 D14): the cell width of the tab-expanded, control-stripped row prefix.
carets = [
    ("load mem xx", 9),
    ("a\tb:#zz", 2),
    ("load\tmem x", 9),
    ("key info e\u0301x", 12),
    ("abc\rdef", 5),
    ("\t\tx", 2),
    ("ab\tc\td", 5),
    ("load mem aes " + "ab " * 40 + "zz", 133),
    ("key info \u65e5\u672c x", 16),
]
cwidths = [80, 200, 40]
print("/// (line, byte offset, console width, rich output)")
print("pub const CARETS: &[(&str, usize, usize, &str)] = &[")
for line, pos in carets:
    row_start = line.rfind("\n", 0, pos) + 1
    row_end = line.find("\n", pos)
    if row_end < 0:
        row_end = len(line)
    prefix = Text(line[row_start:pos])
    prefix.expand_tabs(8)
    text = Text(line[row_start:row_end])
    text.append("\n" + " " * cell_len(prefix.plain))
    text.append("^", style="bold red")
    for w in cwidths:
        out = rendered(text, w)
        print(f"    ({rs(line)}, {len(line[:pos].encode())}, {w}, {rs(out)}),")
print("];")

# rich `cell_len` of single code points (every CELL_WIDTHS range start/end and the code point
# after it) and of grapheme sequences — pinned through the caret column.
table = load_cell_table("latest")
points = set()
for start, end, _ in table.widths:
    for cp in (start, end, end + 1, max(start - 1, 0)):
        points.add(cp)
for c in table.narrow_to_wide:
    points.add(ord(c))
points.update(range(0x80, 0xB0))
skip = {0x0A, 0x0D, 0x07, 0x08, 0x0B, 0x0C}
samples = [chr(cp) for cp in sorted(points) if cp <= 0x10FFFF and not (0xD800 <= cp <= 0xDFFF) and cp not in skip]
samples += [chr(ord(c)) + "\ufe0f" for c in sorted(table.narrow_to_wide)[:40]]
samples += [
    "\U0001f469\u200d\U0001f4bb", "\U0001f468\u200d\U0001f469\u200d\U0001f467", "\u2764\ufe0f",
    "\U0001f1eb\U0001f1f7", "\U0001f44d\U0001f3fd", "a\u200db", "\u200da", "a\u200d", "\ufe0fa",
    "\u200d\u200d", "#\ufe0f\u20e3", "\u0928\u092e\u0938\u094d\u0924\u0947", "e\u0301", "\u00ad",
    "a\tb", "\t", "ab\tc\td", "\u65e5\t\u672c",
]
print("/// (text, rich `cell_len` after rich's own tab expansion)")
print("#[rustfmt::skip]")
print("pub const CELL_LENS: &[(&str, usize)] = &[")
for t in samples:
    expanded = Text(t)
    expanded.expand_tabs(8)
    print(f"    ({rs(t)}, {cell_len(expanded.plain)}),")
print("];")
