"""Differential decode_data vectors: c2@408d6f2 `c2.core.codec.decode_data` outcomes for
tricky inputs (run in the c2 venv; writes Rust to stdout)."""
from c2.core.codec import decode_data
from c2.core.errors import CodecError

def rs(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif ch == "\r": out.append("\\r")
        elif o < 0x20 or 0x7f <= o < 0xa0 or o in (0xa0, 0x2028, 0x2029, 0x3000, 0x85): out.append("\\u{%x}" % o)
        else: out.append(ch)
    return '"' + "".join(out) + '"'

B = "-----BEGIN "
cases = [
    "-----BEGIN X----------END X-----",
    "-----BEGIN X-----AAAA=-----END X-----",
    "-----BEGIN X-----AAAA====-----END X-----",
    "-----BEGIN X-----AA=-----END X-----",
    "-----BEGIN X -----AAAA-----END X-----",
    "-----BEGIN X-----AAAA-----END X -----",
    "-----BEGIN X  Y-----AAAA-----END X  Y-----",
    "-----BEGIN x-----AAAA-----END x-----",
    "-----BEGIN 1-----AAAA-----END 1-----",
    "-----BEGIN -----AAAA-----END -----",
    "-----BEGIN X-----AAAA-----END !----- -----END X-----",
    "-----BEGIN A-----AAAA-----BEGIN B-----BBBB-----END B-----",
    "-----BEGIN X-----\r\nAAAA\r\nAAAA\r\n-----END X-----\r\n",
    "-----BEGIN X-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,00\n\nAAAA\n-----END X-----",
    "-----BEGIN X-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,00\nAAAA\n-----END X-----",
    "-----BEGIN X-----\n\n\nProc-Type: 4,ENCRYPTED\n\nAAAA\n-----END X-----",
    "-----BEGIN X-----\n  Proc-Type:   4,ENCRYPTED  \n\n  AA AA  \n-----END X-----",
    "-----BEGIN X-----\nProc-Type: 4\nnot-a-header line\nAAAA\n-----END X-----",
    "-----BEGIN X-----\nA1: x\nB-2: y\n\nAAAA\nBBBB\n-----END X-----",
    "-----BEGIN X-----Proc-Type: inline AAAA-----END X-----",
    "-----BEGIN X-----\nProc-Type: 4\n\n\n\nAAAA\n-----END X-----",
    "-----BEGIN X-----\nProc-Type: 4\n-----END X-----",
    "-----BEGIN X-----\nAAAA BBBB\n-----END X-----",
    "-----BEGIN X-----\nAAAA\x1cBBBB\n-----END X-----",
    "-----BEGIN X-----\nAAAA BBBB\n-----END X-----",
    "-----BEGIN X-----\nAAAAé\n-----END X-----",
    "-----BEGIN X-----\nAAAA\n-----END X----- trailing -----BEGIN Y-----BBBB-----END Y-----",
    "-----BEGIN X-----\nAAAA\n-----END X----------BEGIN Y-----\nBBBB\n-----END Y-----",
    "  pem:-----BEGIN X-----AAAA-----END X-----  ",
    "pem: -----BEGIN X-----\nDEK-Info: a b c\n\nAAAA\n-----END X-----",
    "PEM:-----BEGIN X-----AAAA-----END X-----",
    "HEX:dead",
    "0Xdead",
    "0x0xdead",
    "hex:0xdead",
    "b64:SGVsbG8",
    "b64:SGVsbG8==",
    "b64:SGVs bG8=",
    " de ad　",
    "de\x1cad",
    "dé",
    "AB==",
    "AR==",
    "AAAA====",
    "A===",
    "SGVsbG8=SGVsbG8=",
    "+/+/",
    "-_-_",
    "0",
    "00",
    "",
    "　",
    "-----BEGIN-----",
    "-----BEGIN X-----",
    "----BEGIN X-----AAAA-----END X-----",
    "x -----BEGIN X-----AAAA-----END X----- y",
    "LS0tLS1CRUdJTiBYLS0tLS1BQUFBLS0tLS1FTkQgWC0tLS0t",
    "2d2d2d2d2d424547494e20582d2d2d2d2d41414141 2d2d2d2d2d454e4420582d2d2d2d2d",
    "2d2d2d2d2d424547494e",
    "LS0tLS1CRUdJTg==",
    "-----BEGIN X-----\n" + "A" * 200 + "\n-----END X-----",
    "-----BEGIN X-----\n" + "QUFB" * 16 + "\n" + "QUFB" * 16 + "\n-----END X-----",
]
print("// Generated by gen_codec_vectors.py (this directory) from c2@408d6f2's decode_data:")
print('// `cd ../c2 && uv run python ../r2/crates/r2-core/tests/support/gen_codec_vectors.py`.')
print('// Do not edit by hand.')
print('// (Regenerate, then `cargo fmt`.)')
print("/// (input, Ok((data hex, format)) | Err((message, hint)))")
print("pub type Outcome = Result<(&'static str, &'static str), (&'static str, Option<&'static str>)>;")
print("pub const DECODE: &[(&str, Outcome)] = &[")
for text in cases:
    try:
        data, fmt = decode_data(text)
        print(f"    ({rs(text)}, Ok(({rs(data.hex())}, {rs(fmt.value)}))),")
    except CodecError as exc:
        hint = f"Some({rs(exc.hint)})" if exc.hint is not None else "None"
        print(f"    ({rs(text)}, Err(({rs(exc.message)}, {hint}))),")
    except Exception as exc:  # c2 crash paths (r2 maps them to Codec, see the test)
        print(f"    // c2 CRASH: {type(exc).__name__}: {exc}")
        print(f"    ({rs(text)}, Err((\"<c2 crash: {type(exc).__name__}>\", None))),")
print("];")
