"""CPython 3.12 vectors for r2_core::text (repr, bytes repr, int, fromhex, PurePosixPath,
difflib.get_close_matches); run in the c2 venv, writes Rust to stdout."""
import difflib, pathlib, os, errno
def rs(s):
    out=[]
    for ch in s:
        o=ord(ch)
        if ch=="\\": out.append("\\\\")
        elif ch=='"': out.append('\\"')
        elif ch=="\n": out.append("\\n")
        elif ch=="\t": out.append("\\t")
        elif ch=="\r": out.append("\\r")
        elif o<0x20 or 0x7f<=o<0xa0 or o in (0x2028,0x2029,0xad,0x200b,0xfeff,0x3000,0x1680,0xa0) or 0xd800<=o<0xe000 or o>=0xe0000 or (0x2000<=o<=0x200f) or (0x202a<=o<=0x202f) or (0x2060<=o<=0x206f) or o==0x85 or (0xe000<=o<=0xf8ff) or (0x10000 <= o and not ch.isprintable()):
            out.append("\\u{%x}" % o)
        else: out.append(ch)
    return '"'+"".join(out)+'"'
reprs = ["", "abc", "it's", 'say "hi"', "both ' and \"", "back\\slash", "tab\there", "nl\nx", "cr\rx",
 "\x00\x01\x1f\x7f", "\x80\x9f\xa0\xad", "é ü ß", "ключ", "日本語", "  ", "​﻿", "\U0001f600",
 "\U000e0001", "", "\U0010ffff", "͸", "a b", "　", "\x1c\x1d", "'", '"', "'\"", "\x0b\x0c", "\U0001d7d8", "̀a"]
print('// Generated by gen_text_vectors.py (this directory) with CPython 3.12.3 in the c2@408d6f2 venv:')
print('// `cd ../c2 && uv run python ../r2/crates/r2-core/tests/support/gen_text_vectors.py`. Do not edit')
print('// by hand. Non-ASCII int() inputs that CPython accepts are recorded as None (r2 is ASCII-only, D18).')
print('// (Regenerate, then `cargo fmt`.)')
print("pub const PY_REPR: &[(&str, &str)] = &[")
for s in reprs: print(f"    ({rs(s)}, {rs(repr(s))}),")
print("];")
brs = [b"", b"abc", b"it's", b'say "hi"', b"both ' and \"", b"\\", b"\t\n\r", b"\x00\x7f\x80\xff", bytes(range(0x1e,0x22))]
print("pub const PY_BYTES_REPR: &[(&[u8], &str)] = &[")
for b in brs: print(f"    (&[{', '.join(str(x) for x in b)}], {rs(repr(b))}),")
print("];")
ints = ["0","7","-7","+7"," 42 ","\t42\n","1_000","1__000","_1","1_","007","-0","","+","-","0x10","0X10","0x_10","0x__10","10_","ff","FF","0xff","-0xff","+0x1F"," - 1","--1","1 2","12a"," 12 ","٣","9"*38,"9"*39,"170141183460469231731687303715884105727","170141183460469231731687303715884105728","-170141183460469231731687303715884105728","-170141183460469231731687303715884105729","0x","0x_","x10","1e3","1.0","\x1c5\x1f"]
print("/// (text, int(text, 10) or None, int(text, 16) or None) — None also when outside i128.")
print("pub const PY_INT: &[(&str, Option<i128>, Option<i128>)] = &[")
def tryint(s, b):
    try:
        v = int(s, b)
    except ValueError:
        return "None"
    if not (-2**127 <= v < 2**127): return "None"
    if any(not c.isascii() for c in s.strip()) : return "NONASCII"
    return f"Some({v})"
for s in ints:
    a, b = tryint(s,10), tryint(s,16)
    if "NONASCII" in (a,b):
        # CPython accepts other Unicode digits; r2 is ASCII-only (D18) → None
        a = "None" if a == "NONASCII" else a; b = "None" if b == "NONASCII" else b
    print(f"    ({rs(s)}, {a}, {b}),")
print("];")
hexes = ["", "0a1b", "0A 1B", " 0a 1b ", "0 a", "0a1", "zz", "0a\t1b\n", "0a\x0b1b", "0a\x0c1b", "0a 1b", "é", "0x0a", "00ff", "a"]
print("pub const PY_FROMHEX: &[(&str, Option<&[u8]>)] = &[")
for s in hexes:
    try:
        v = bytes.fromhex(s); r = f"Some(&[{', '.join(str(x) for x in v)}])"
    except ValueError: r = "None"
    print(f"    ({rs(s)}, {r}),")
print("];")
paths = ["", ".", "./", "./x", "a/./b/", "//x", "///x", "////x", "/", "//", "///", "a//b", "../x", "a/../b", "~/x", "x/", "/a/b/c/", "a/.", "./.", ". /x", "out.bin", "./out.bin", "dir/./sub//file.pem", "//x/../y"]
print("pub const PY_PATH_POSIX: &[(&str, &str)] = &[")
for p in paths: print(f"    ({rs(p)}, {rs(str(pathlib.PurePosixPath(p)))}),")
print("];")
aes = ["ecb","cbc","gcm","ctr","cmac","gmac"]
cmds = ["help","exit","quit","clear","config","providers","slots","login","logout","keys","key","generate","load","export","csr","delete","encrypt","decrypt","sign","verify","derive","ops","copy"]
hashes = ["sha1","sha224","sha256","sha384","sha512"]
cases = [("sha", hashes, 3), ("ebc", aes, 3), ("cb", aes, 3), ("decrept", cmds, 3), ("aecrypt", cmds, 3), ("cps", cmds, 3), ("helpp", ["help","exit","quit"], 3), ("zzzzzz", ["help","exit"], 3), ("", ["", "a"], 3), ("abc", ["abc","abc","cba","bca"], 3), ("key", cmds, 1), ("keys", cmds, 5), ("x"*250, ["x"*240 + "y"*10, "x"*100], 3), ("ab", ["ab"]*4 + ["ba"], 2), ("logn", cmds, 3), ("sign", ["sign","sing","singe","signs"], 4), ("CKA_LABL", ["CKA_LABEL","CKA_TOKEN","CKA_ID"], 1)]
print("pub const CLOSE_MATCHES: &[(&str, &[&str], usize, &[&str])] = &[")
for word, poss, n in cases:
    res = difflib.get_close_matches(word, poss, n=n)
    print(f"    ({rs(word)}, &[{', '.join(rs(p) for p in poss)}], {n}, &[{', '.join(rs(r) for r in res)}]),")
print("];")
