#![allow(dead_code)]
// R0 skeleton — owner R7 (generated from spec §4)
// ---- spec §4.9.6 block 0
use crate::context::AppContext;
use crate::parser::BoundArgs;
use crate::repl::{CommandTable, Flow};
use std::rc::Rc;

/// One console command. Object-safe.
pub trait Command {
    fn name(&self) -> &'static str;
    fn summary(&self) -> &'static str;
    fn usage(&self) -> &'static str;
    /// Boolean `--options` (they consume no value token).
    fn flags(&self) -> &'static [&'static str] {
        &[]
    }
    fn run(&self, ctx: &AppContext, args: &BoundArgs) -> r2_core::Result<Flow>;
    /// Completion candidates. `tokens` = every token of the line (command name included,
    /// and the partial token under the cursor when there is one); `cursor_token` = that
    /// partial token ("" at a new token). Candidates are FULL replacement tokens, filtered by
    /// prefix and de-duplicated by the completer. Must never call `ctx.io`, must never load
    /// a PKCS#11 library (use `completer::browsable`), and swallows every error.
    fn complete(&self, ctx: &AppContext, tokens: &[String], cursor_token: &str) -> Vec<String> {
        let _ = (ctx, tokens, cursor_token);
        Vec::new()
    }
}

// Generated by build.rs (see below):
include!(concat!(env!("OUT_DIR"), "/command_modules.rs"));

/// Fresh scan of every command module. Duplicate name → Config "duplicate command name
/// '{name}' (module '{module}')".
pub fn discover_commands() -> r2_core::Result<CommandTable> {
    Err(r2_core::ConsoleError::not_implemented("R7"))
}
/// Cached `discover_commands()` (thread-local; the module set is fixed per build).
pub fn all_commands() -> r2_core::Result<Rc<CommandTable>> {
    Err(r2_core::ConsoleError::not_implemented("R7"))
}
