// Command trait + module registration (spec §4.9.6; owner R7) — c2 `console/commands/
// __init__.py`. Every file `src/commands/<stem>.rs` exports `pub fn commands()`; build.rs
// generates the module list. There is NO central registration table.
use std::cell::RefCell;
use std::rc::Rc;

use crate::context::AppContext;
use crate::parser::BoundArgs;
use crate::repl::{CommandTable, Flow};

/// One console command. Object-safe.
pub trait Command {
    fn name(&self) -> &'static str;
    fn summary(&self) -> &'static str;
    fn usage(&self) -> &'static str;
    /// Boolean `--options` (they consume no value token).
    fn flags(&self) -> &'static [&'static str] {
        &[]
    }
    fn run(&self, ctx: &AppContext, args: &BoundArgs) -> r2_core::Result<Flow>;
    /// Completion candidates. `tokens` = every token of the line (command name included,
    /// and the partial token under the cursor when there is one); `cursor_token` = that
    /// partial token ("" at a new token). Candidates are FULL replacement tokens, filtered by
    /// prefix and de-duplicated by the completer. Must never call `ctx.io`, must never load
    /// a PKCS#11 library (use `completer::browsable`), and swallows every error.
    fn complete(&self, ctx: &AppContext, tokens: &[String], cursor_token: &str) -> Vec<String> {
        let _ = (ctx, tokens, cursor_token);
        Vec::new()
    }
}

// Generated by build.rs (see below):
include!(concat!(env!("OUT_DIR"), "/command_modules.rs"));

/// Fresh scan of every command module. Duplicate name → Config "duplicate command name
/// '{name}' (module '{module}')".
pub fn discover_commands() -> r2_core::Result<CommandTable> {
    collect_commands(module_commands())
}

/// The discovery merge over (module stem, commands) pairs, in module order.
pub(crate) fn collect_commands(
    modules: Vec<(&'static str, Vec<Box<dyn Command>>)>,
) -> r2_core::Result<CommandTable> {
    let mut table = CommandTable::new();
    for (module, commands) in modules {
        for command in commands {
            let name = command.name();
            if table.contains_key(name) {
                return Err(r2_core::ConsoleError::config(format!(
                    "duplicate command name '{name}' (module '{module}')"
                )));
            }
            table.insert(name, Rc::from(command));
        }
    }
    Ok(table)
}

thread_local! {
    static CACHE: RefCell<Option<Rc<CommandTable>>> = const { RefCell::new(None) };
}

/// Cached `discover_commands()` (thread-local; the module set is fixed per build).
pub fn all_commands() -> r2_core::Result<Rc<CommandTable>> {
    if let Some(table) = CACHE.with(|cache| cache.borrow().clone()) {
        return Ok(table);
    }
    let table = Rc::new(discover_commands()?);
    CACHE.with(|cache| *cache.borrow_mut() = Some(Rc::clone(&table)));
    Ok(table)
}
