// Grammar-aware completion and highlighting (spec §4.9.7, §4.9.9, §5.1; owner R7) — the
// port of c2 `console/completer.py`.
//
// First token → command names; later tokens → the command's own `complete` hook. Refs
// complete only for memory and logged-in providers (completion never triggers a PKCS#11
// library load, §6); logged-out or unavailable providers complete just `provider:`. File
// options complete filesystem paths. Spans are BYTE ranges of the raw token under the cursor.
use std::rc::Rc;

use indexmap::IndexMap;
use nu_ansi_term::{Color, Style};
use r2_core::keys::{KeyInfo, display_refs};
use r2_core::text::is_py_space;
use r2_provider::{AuthState, Provider};
use reedline::{Span, StyledText, Suggestion};

use crate::context::AppContext;
use crate::io::LineAssist;
use crate::parser::{Token, line_is_complete, tokenize};
use crate::repl::CommandTable;

/// Provider instance names starting with `prefix` (any state — names are config data).
pub fn complete_provider_names(ctx: &AppContext, prefix: &str) -> Vec<String> {
    ctx.providers
        .all()
        .iter()
        .map(|provider| provider.name().to_owned())
        .filter(|name| name.starts_with(prefix))
        .collect()
}
/// `provider:label` candidates (§5.1/§6): no ':' yet → every "name:" matching the prefix;
/// with a provider prefix → that provider's `display_refs` starting with the prefix — only
/// when `browsable(provider)` and list_keys succeeds, else just "name:" — plus, once the
/// prefix extends past a full label with '#' or ':', the §4.3 selector continuations
/// (`prov:label:<class>`, and for keys with an id `prov:label#<idhex>` and
/// `prov:label#<idhex>:<class>`), keeping a string generated by several keys only when they
/// form one distinct-class family with one id. Order: refs first, then continuations,
/// de-duplicated.
pub fn complete_refs(ctx: &AppContext, prefix: &str) -> Vec<String> {
    let Some((provider_name, _)) = prefix.split_once(':') else {
        return ctx
            .providers
            .all()
            .iter()
            .map(|provider| format!("{}:", provider.name()))
            .filter(|candidate| candidate.starts_with(prefix))
            .collect();
    };
    let Ok(provider) = ctx.providers.get(provider_name) else {
        return Vec::new();
    };
    let bare = vec![format!("{}:", provider.name())];
    if !browsable(provider.as_ref()) {
        return bare;
    }
    let Ok(keys) = provider.list_keys() else {
        return bare;
    };
    let mut candidates: Vec<String> = display_refs(&keys)
        .into_iter()
        .filter(|text| text.starts_with(prefix))
        .collect();
    for text in selector_candidates(&keys, prefix) {
        if !candidates.contains(&text) {
            candidates.push(text);
        }
    }
    candidates
}

/// §4.3 selector continuations once the prefix extends past a full label (c2
/// `_selector_candidates`). A string generated by several keys survives only when they form
/// one distinct-class family with one id (the find_key collapse rule) — ambiguous refs are
/// never offered.
fn selector_candidates(keys: &[KeyInfo], prefix: &str) -> Vec<String> {
    let mut generated: IndexMap<String, Vec<&KeyInfo>> = IndexMap::new();
    for info in keys {
        let stem = format!("{}:{}", info.key_ref.provider, info.key_ref.label);
        let rest = prefix.strip_prefix(stem.as_str()).unwrap_or("");
        if !(rest.starts_with('#') || rest.starts_with(':')) {
            continue; // provider/label stage — the keys-table menu suffices
        }
        let token = info.key_class.token();
        let mut forms = vec![format!("{stem}:{token}")];
        if info.key_ref.key_id.is_some() {
            let plain = info.key_ref.display();
            forms.push(format!("{plain}:{token}"));
            forms.insert(1, plain);
        }
        for text in forms {
            if text.starts_with(prefix) {
                generated.entry(text).or_default().push(info);
            }
        }
    }
    generated
        .into_iter()
        .filter(|(_, infos)| {
            if infos.len() == 1 {
                return true;
            }
            let first_id = &infos[0].key_ref.key_id;
            let one_id = infos.iter().all(|info| &info.key_ref.key_id == first_id);
            let mut classes: Vec<_> = infos.iter().map(|info| info.key_class).collect();
            classes.sort();
            classes.dedup();
            one_id && classes.len() == infos.len()
        })
        .map(|(text, _)| text)
        .collect()
}

/// Filesystem candidates (§5.1 PathCompleter rule): FULL replacement tokens re-carrying the
/// typed directory part verbatim (`~` stays unexpanded in the candidate, expanded for
/// listing); directories get a trailing '/'; hidden entries only when the partial name
/// starts with '.'; sorted; unreadable directories → empty. Never errors.
pub fn complete_paths(prefix: &str) -> Vec<String> {
    let (dir_prefix, partial) = match prefix.rfind('/') {
        Some(slash) => (&prefix[..=slash], &prefix[slash + 1..]),
        None => ("", prefix),
    };
    let listing_dir = if dir_prefix.is_empty() {
        std::path::PathBuf::from(".")
    } else {
        r2_config::dirs::expand_user(dir_prefix)
    };
    let Ok(entries) = std::fs::read_dir(&listing_dir) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| entry.file_name().into_string().ok())
        .collect();
    names.sort();
    names
        .into_iter()
        .filter(|name| name.starts_with(partial))
        .filter(|name| !name.starts_with('.') || partial.starts_with('.'))
        .map(|name| {
            let mut candidate = format!("{dir_prefix}{name}");
            if listing_dir.join(&name).is_dir() {
                candidate.push('/');
            }
            candidate
        })
        .collect()
}
/// True when listing keys cannot trigger a login or a library load: status().auth is
/// NotRequired or LoggedIn.
pub fn browsable(provider: &dyn Provider) -> bool {
    matches!(
        provider.status().auth,
        AuthState::NotRequired | AuthState::LoggedIn
    )
}

/// The REPL's completion + highlighting engine (installed by `run_repl` through
/// `install_line_assist`; c2 `ConsoleCompleter`).
pub(crate) struct ConsoleAssist {
    ctx: Rc<AppContext>,
    commands: Rc<CommandTable>,
}

impl ConsoleAssist {
    pub(crate) fn new(ctx: Rc<AppContext>, commands: Rc<CommandTable>) -> Self {
        Self { ctx, commands }
    }

    /// True when `token` names a registered provider's `provider:` ref.
    fn is_provider_ref(&self, token: &str) -> bool {
        token
            .split_once(':')
            .is_some_and(|(name, _)| self.ctx.providers.get(name).is_ok())
    }

    /// The menu text of a candidate: path-like candidates show their last component.
    fn display(&self, candidate: &str) -> Option<String> {
        if self.is_provider_ref(candidate) {
            return None;
        }
        let trimmed = candidate.strip_suffix('/').unwrap_or(candidate);
        let (_, base) = trimmed.rsplit_once('/')?;
        let slash = if candidate.ends_with('/') { "/" } else { "" };
        Some(format!("{base}{slash}"))
    }
}

/// c2 `ConsoleCompleter._completions` over byte spans (§4.9.7 completion contract).
pub(crate) fn complete_line(
    ctx: &AppContext,
    commands: &CommandTable,
    line: &str,
    pos: usize,
) -> Vec<(String, Span)> {
    let Some(text) = line.get(..pos) else {
        return Vec::new();
    };
    if !line_is_complete(text) {
        return Vec::new(); // inside a quoted paste — never complete
    }
    let Ok(tokens) = tokenize(text) else {
        return Vec::new();
    };
    let at_new_token = text.chars().next_back().is_none_or(is_py_space);
    let cursor: Option<&Token> = if at_new_token { None } else { tokens.last() };
    let cursor_token = cursor.map_or("", |token| token.text.as_str());
    let span = Span::new(cursor.map_or(pos, |token| token.pos), pos);
    let candidates: Vec<String> = if tokens.is_empty() || (tokens.len() == 1 && !at_new_token) {
        commands.keys().map(|name| (*name).to_owned()).collect()
    } else {
        let Some(command) = commands.get(tokens[0].text.as_str()) else {
            return Vec::new();
        };
        let texts: Vec<String> = tokens.iter().map(|token| token.text.clone()).collect();
        command.complete(ctx, &texts, cursor_token)
    };
    let mut candidates: Vec<String> = candidates
        .into_iter()
        .filter(|candidate| candidate.starts_with(cursor_token))
        .collect();
    candidates.sort();
    candidates.dedup();
    candidates
        .into_iter()
        .map(|candidate| (candidate, span))
        .collect()
}

impl LineAssist for ConsoleAssist {
    fn complete(&self, line: &str, pos: usize) -> Vec<Suggestion> {
        complete_line(&self.ctx, &self.commands, line, pos)
            .into_iter()
            .map(|(value, span)| Suggestion {
                display_override: self.display(&value),
                value,
                span,
                append_whitespace: false,
                ..Suggestion::default()
            })
            .collect()
    }

    fn highlight(&self, line: &str) -> StyledText {
        let mut styled = StyledText::new();
        let (tokens, open_quote) = match tokenize(line) {
            Ok(tokens) => (tokens, None),
            Err(err) => {
                // style what precedes the open quote; the rest is a (still open) string
                let open = err.parse_position().map_or(0, |(_, pos)| pos);
                let before = line.get(..open).unwrap_or("");
                (tokenize(before).unwrap_or_default(), Some(open))
            }
        };
        let mut at = 0;
        for (index, token) in tokens.iter().enumerate() {
            if token.pos > at {
                styled.push((Style::new(), line[at..token.pos].to_owned()));
            }
            let raw = &line[token.pos..token.end];
            let style = if index == 0 {
                // dispatch looks up the token TEXT (a quoted command name runs too)
                if self.commands.contains_key(token.text.as_str()) {
                    Style::new().fg(Color::Green).bold()
                } else {
                    Style::new().fg(Color::Red)
                }
            } else if token.quoted {
                Style::new().fg(Color::Yellow)
            } else if raw.starts_with("--") {
                Style::new().fg(Color::Blue)
            } else if raw.contains('=') {
                Style::new().fg(Color::Magenta)
            } else if self.is_provider_ref(raw) {
                Style::new().fg(Color::Cyan)
            } else {
                Style::new()
            };
            styled.push((style, raw.to_owned()));
            at = token.end;
        }
        if let Some(open) = open_quote {
            if open > at {
                styled.push((Style::new(), line[at..open].to_owned()));
            }
            let style = if tokens.is_empty() {
                Style::new().fg(Color::Red)
            } else {
                Style::new().fg(Color::Yellow)
            };
            styled.push((style, line[open..].to_owned()));
            at = line.len();
        }
        if at < line.len() {
            styled.push((Style::new(), line[at..].to_owned()));
        }
        styled
    }
}
