// R0 skeleton — owner R7 (generated from spec §4)
// ---- spec §4.9.9 block 0
use r2_provider::Provider;

use crate::context::AppContext;

/// Provider instance names starting with `prefix` (any state — names are config data).
pub fn complete_provider_names(ctx: &AppContext, prefix: &str) -> Vec<String> {
    let _ = (ctx, prefix);
    unimplemented!("R7")
}
/// `provider:label` candidates (§5.1/§6): no ':' yet → every "name:" matching the prefix;
/// with a provider prefix → that provider's `display_refs` starting with the prefix — only
/// when `browsable(provider)` and list_keys succeeds, else just "name:" — plus, once the
/// prefix extends past a full label with '#' or ':', the §4.3 selector continuations
/// (`prov:label:<class>`, and for keys with an id `prov:label#<idhex>` and
/// `prov:label#<idhex>:<class>`), keeping a string generated by several keys only when they
/// form one distinct-class family with one id. Order: refs first, then continuations,
/// de-duplicated.
pub fn complete_refs(ctx: &AppContext, prefix: &str) -> Vec<String> {
    let _ = (ctx, prefix);
    unimplemented!("R7")
}
/// Filesystem candidates (§5.1 PathCompleter rule): FULL replacement tokens re-carrying the
/// typed directory part verbatim (`~` stays unexpanded in the candidate, expanded for
/// listing); directories get a trailing '/'; hidden entries only when the partial name
/// starts with '.'; sorted; unreadable directories → empty. Never errors.
pub fn complete_paths(prefix: &str) -> Vec<String> {
    let _ = prefix;
    unimplemented!("R7")
}
/// True when listing keys cannot trigger a login or a library load: status().auth is
/// NotRequired or LoggedIn.
pub fn browsable(provider: &dyn Provider) -> bool {
    let _ = provider;
    unimplemented!("R7")
}
