"""Generate the c2 interop vectors of crates/r2-memory/tests/support/c2_vectors.rs.

Run inside c2's venv (c2@408d6f2):  cd /home/user/c2 && uv run python \
    /path/to/r2/crates/r2-memory/tests/support/gen_c2_vectors.py > c2_vectors.rs

Every blob is produced by c2's own MemoryProvider.wrap_key (the RSA-AES-KEY-WRAP hybrid,
spec §5.5: OAEP(hash, mgf_hash, label)(32 random bytes) ‖ KWP(those bytes, payload)) and by
pyca's keywrap for the Utimaco-dialect AES-KEY-WRAP-PAD blob, so the Rust tests prove the
r2 MemoryProvider reads c2's bytes (and r2's own blobs are checked by an independent
decoder in the tests).
"""

from cryptography.hazmat.primitives import keywrap, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa

from c2.core.keys import KeyAlgorithm, KeyClass, KeyMaterial
from c2.providers.base import MechanismInvocation
from c2.providers.memory import MemoryProvider


def h(data: bytes) -> str:
    return data.hex()


def const(name: str, data: bytes) -> None:
    print(f'pub const {name}: &str = "{h(data)}";')


rsa_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
rsa_pkcs8 = rsa_key.private_bytes(
    serialization.Encoding.DER, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
)
rsa_spki = rsa_key.public_key().public_bytes(
    serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
)
ec_key = ec.generate_private_key(ec.SECP256R1())
ec_pkcs8 = ec_key.private_bytes(
    serialization.Encoding.DER, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
)
aes_target = bytes(range(0x40, 0x60))

p = MemoryProvider("c2")
pub = p.import_key(KeyMaterial(KeyAlgorithm.RSA, KeyClass.PUBLIC, rsa_spki), "kek-pub")
aes = p.import_key(KeyMaterial(KeyAlgorithm.AES, KeyClass.SECRET, aes_target), "aes")
ecp = p.import_key(KeyMaterial(KeyAlgorithm.EC, KeyClass.PRIVATE, ec_pkcs8), "ec")

blob_default = p.wrap_key(pub, MechanismInvocation("RSA-AES-KEY-WRAP", {}), aes)
blob_params = p.wrap_key(
    pub,
    MechanismInvocation(
        "RSA-AES-KEY-WRAP", {"hash": "sha384", "mgf_hash": "sha1", "label": b"r2-label"}
    ),
    ecp,
)
kek = bytes(range(32))
pad = 8 - len(ec_pkcs8) % 8 or 8
utimaco = keywrap.aes_key_wrap(kek, ec_pkcs8 + bytes([pad]) * pad)
kwp = keywrap.aes_key_wrap_with_padding(kek, ec_pkcs8)

print("// Generated by gen_c2_vectors.py in c2's venv (c2@408d6f2, pyca 49.0.0). Do not edit.")
const("RSA_PKCS8", rsa_pkcs8)
const("EC_PKCS8", ec_pkcs8)
const("AES_TARGET", aes_target)
const("RSA_AES_KEY_WRAP_DEFAULT_BLOB", blob_default)
const("RSA_AES_KEY_WRAP_SHA384_MGF1_LABEL_BLOB", blob_params)
const("KEK", kek)
const("UTIMACO_PAD_DIALECT_BLOB", utimaco)
const("RFC5649_KWP_BLOB", kwp)
