[package]
name = "r2-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
softhsm = []

[dependencies]
openssl = { workspace = true }
der = { workspace = true }
spki = { workspace = true }
x509-cert = { workspace = true }
const-oid = { workspace = true }
secrecy = { workspace = true }
zeroize = { workspace = true }
indexmap = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
difflib = { workspace = true }
comfy-table = { workspace = true }
anstream = { workspace = true }
anstyle = { workspace = true }
unicode-width = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
r2-testkit = { workspace = true }
